baseurl                  = "https://sam-barrett.codes/Notes/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Welcome to my Notes Repo!"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
katex 			 = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "My University Notes Site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Notes"

[[params.mainMenu]]
    link = "/Notes/modules/neural-computation/"
    text = "Neural Computation"
[[params.mainMenu]]
    link = "/Notes/modules/machine-learning/"
    text = "Machine Learning"

[[params.mainMenu]]
    link = "/Notes/modules/parallel-distributed/"
    text = "Distributed and Parallel Computing"

[imaging]
    quality = 75
