name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: cd utils && npm install
    - name: Transpile md to html
      run: sudo apt install zsh && make CI
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name:  out
        path: out/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: resources
        path: resources/
  
  deploy:
    needs: build
    name: Deploy to Firebase bucket
    runs-on: ubuntu-latest
    steps: 
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: out
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: resources
      - name: Deploy to Firebase Storage Bucket
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.APPLICATION_CREDENTIALS}}
          CLI: gsutil
        with:
          args: cp -r {out,resources} gs://barrett370-notes.appspot.com


      
